// clang-format off
// *INDENT-OFF*
// Generated by https://github.com/Nigh/picture-to-array
// Version:v1.50
#ifndef _05b03ff87ff4925ca8dc9f40ff541ce518073257_
#define _05b03ff87ff4925ca8dc9f40ff541ce518073257_
#include "bitmap.h"

extern const sBITMAP ad1_bmp;
extern const sBITMAP ad2_bmp;
#endif
