// clang-format off
// *INDENT-OFF*
// Generated by https://github.com/Nigh/picture-to-array
// Version:v1.50
#ifndef _d207944d75f3e73c8793bf063669e57e778c8a9c_
#define _d207944d75f3e73c8793bf063669e57e778c8a9c_
#include "bitmap.h"

extern const sBITMAP ad1_bmp;
extern const sBITMAP ad2_bmp;
extern const sBITMAP dino_back_leg_bmp;
extern const sBITMAP dino_crashed_bmp;
extern const sBITMAP dino_front_leg_bmp;
extern const sBITMAP dino_jumps_bmp;
extern const sBITMAP tree_big_bmp;
extern const sBITMAP tree_small_bmp;
#endif
